spring:
  application:
    name: MasterBook-api
  datasource:
    url: jdbc:h2:mem:masterbook
    driver-class-name: org.h2.Driver
    username: user
    password: 123
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.H2Dialect